version: '3.7'
services:
  db:
   image: postgres
   restart: always
   ports:
     - 5432:5432
   environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
